routes/web.php
<?php

Route::get('/', function(){return redirect('/home');});
Route::get('/home', 'UserController@home')->name('home');
Route::get('/blog', 'UserController@blog')->name('blog');
Route::get('/blog/{slug}', 'UserController@show_article')->name('blog.show');
Route::get('/destination', 'UserController@destination')->name('destination');
Route::get('/destination/{slug}', 'UserController@show_destination')->name('destination.show');
Route::get('/produk/{slug}', 'UserController@show_produk')->name('user.show_produk');
Route::get('/artikel/{slug}', 'UserController@show_artikel')->name('user.show_artikel');
Route::get('/contact', 'UserController@contact')->name('contact');
Route::get('/slide', 'UserController@slide')->name('slide');

Route::prefix('admin')->group(function(){

  Route::get('/', function(){
    return view('auth/login');
  });

  // handle route register
  Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
  })->name("register");

  Auth::routes();

  // Route Dashboard
  Route::get('/dashboard', 'DashboardController@index')->middleware('auth');

  // route categories
  Route::get('/categories/{category}/restore', 'CategoryController@restore')->name('categories.restore');
  Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');
  Route::get('/ajax/categories/search', 'CategoryController@ajaxSearch');
  Route::resource('categories', 'CategoryController')->middleware('auth');

  // route article
  Route::post('/articles/upload', 'ArticleController@upload')->name('articles.upload')->middleware('auth');
  Route::resource('/articles', 'ArticleController')->middleware('auth');

  // route destination
  Route::resource('/destinations', 'DestinationController')->middleware('auth');

  // Route about
  Route::get('/abouts', 'AboutController@index')->name('abouts.index')->middleware('auth');
  Route::get('/abouts/{about}/edit', 'AboutController@edit')->name('abouts.edit')->middleware('auth');
  Route::put('/abouts/{about}', 'AboutController@update')->name('abouts.update')->middleware('auth');
  // Route::resource('abouts', 'AboutController')->middleware('auth');

    // Route slide
    Route::resource('/slide', 'SlideController')->middleware('auth');
    Route::get('/slide', 'SlideController@index')->name('slide.index')->middleware('auth');
    Route::get('/slide/{slide}/edit', 'SlideController@edit')->name('slide.edit')->middleware('auth');
    Route::put('/slide/{slide}', 'SlideController@update')->name('slide.update')->middleware('auth');

    // Route online
    Route::resource('/online', 'OnlineController')->middleware('auth');
    Route::get('/online', 'OnlineController@index')->name('online.index')->middleware('auth');
    Route::get('/online/{online}/edit', 'OnlineController@edit')->name('online.edit')->middleware('auth');
    Route::put('/online/{online}', 'OnlineController@update')->name('online.update')->middleware('auth');

    // Route sosmed
    Route::resource('/sosmed', 'SosmedController')->middleware('auth');
    Route::get('/sosmed', 'SosmedController@index')->name('sosmed.index')->middleware('auth');
    Route::get('/sosmed/{sosmed}/edit', 'SosmedController@edit')->name('sosmed.edit')->middleware('auth');
    Route::put('/sosmed/{sosmed}', 'SosmedController@update')->name('sosmed.update')->middleware('auth');

    // Route layout
    Route::resource('/layout', 'LayoutController')->middleware('auth');
    Route::get('/layout', 'LayoutController@index')->name('layout.index')->middleware('auth');
    Route::get('/layout/{layout}/edit', 'LayoutController@edit')->name('layout.edit')->middleware('auth');
    Route::put('/layout/{layout}', 'LayoutController@update')->name('layout.update')->middleware('auth');

    // Route layout
    Route::resource('/produk', 'ProdukController')->middleware('auth');
    Route::get('/produk', 'ProdukController@index')->name('produk.index')->middleware('auth');
    Route::get('/produk/{produk}/edit', 'ProdukController@edit')->name('produk.edit')->middleware('auth');
    Route::put('/produk/{produk}', 'ProdukController@update')->name('produk.update')->middleware('auth');

    // Route artikel
    Route::resource('/artikel', 'ArtikelController')->middleware('auth');
    Route::get('/artikel', 'ArtikelController@index')->name('artikel.index')->middleware('auth');
    Route::get('/artikel/{artikel}/edit', 'ArtikelController@edit')->name('artikel.edit')->middleware('auth');
    Route::put('/artikel/{artikel}', 'ArtikelController@update')->name('artikel.update')->middleware('auth');
});

app/Produk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    public $table = "produk";
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;
use App\Produk;
use Illuminate\Http\Request;
use File;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status     = $request->get('status');
        $keyword    = $request->get('keyword') ? $request->get('keyword') : '';
        $category   = $request->get('c') ? $request->get('c') : '';

        if($status){
            $produk = Produk::where('status', strtoupper($status))
                ->paginate(10);

        }else{
            $produk = Produk::where('title', 'LIKE', "%$keyword%")
                ->paginate(10);
        }

        return view('produk.index', compact('produk'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('produk.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Validator::make($request->all(),[
            'title'      => 'required|min:2|max:200',
            'image'      => 'required',
        ])->validate();

        $new_Produk               = new \App\Produk();
        $new_Produk->title        = $request->get('title');
        $new_Produk->kategori        = $request->get('kategori');
        $new_Produk->description        = $request->get('description');
        $new_Produk->weight        = $request->get('weight');
        $new_Produk->price        = $request->get('price');

        if($request->file('image')){
            $nama_file = time()."_".$request->file('image')->getClientOriginalName();
            $image_path = $request->file('image')->move('produk_image', $nama_file);
            $new_Produk->image = $nama_file;
        }
        $new_Produk->save();

        return redirect()->route('produk.index')->with('success', 'Product successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
//    public function show($id)
//    {
//
//    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $produk = Produk::findOrFail($id);
        return view('produk.edit', compact('produk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $produk = Produk::findOrFail($id);

        $produk->title        = $request->get('title');
        $produk->kategori        = $request->get('kategori');
        $produk->description        = $request->get('description');
        $produk->weight        = $request->get('weight');
        $produk->price        = $request->get('price');

        if($request->file('image')){
            if($produk->image){
                File::delete('produk_image/'.$produk->image);
            }
            $nama_file = time()."_".$request->file('image')->getClientOriginalName();
            $new_image = $request->file('image')->move('produk_image', $nama_file);
            $produk->image = $nama_file;
        }

        $produk->save();
        return redirect()->route('produk.index')->with('success', 'Product successfully update.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produk = Produk::findOrFail($id);
        if($produk->image){
            File::delete('produk_image/'.$produk->image);
        }
        $produk->forceDelete();

        return redirect()->route('produk.index')->with('success', 'Product successfully deleted.');
    }
}

resources/views/produk/create.blade.php
@extends('layouts.admin')

@section('title', 'Create Produk')

@section('breadcrumbs', 'Produk' )

@section('second-breadcrumb')
    <li>Create</li>
@endsection

@section('css')
    <script src="/templateEditor/ckeditor/ckeditor.js"></script>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-12 mb-3">
                        <h3 align="center"></h3>
                    </div>
                    <form action="{{route('produk.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="col-12">
                            <div class="mb-1">
                                <label for="title" class="font-weight-bold">Category</label>
                                <select name="kategori" id="kategori" class="form-control {{$errors->first('kategori') ? "is-invalid" : ""}}"  value="{{old('kategori')}}">
                                    <option value="Facial Wash">Facial Wash</option>
                                    <option value="Serum">Serum</option>
                                    <option value="Sunscreen">Sunscreen</option>
                                    <option value="Toner">Toner</option>
                                </select>
                                <div class="invalid-feedback"> {{$errors->first('kategori')}}</div>
                            </div>
                            <div class="mb-1">
                                <label for="title" class="font-weight-bold">Name</label>
                                <input type="text" name="title" placeholder="Product Name..." class="form-control {{$errors->first('title') ? "is-invalid" : ""}}" value="{{old('title')}}" required>
                                <div class="invalid-feedback"> {{$errors->first('title')}}</div>
                            </div>
                            <div class="mb-1">
                                <label for="title" class="font-weight-bold">Description</label>
                                <textarea type="text" name="description" placeholder="Product Description..." class="form-control {{$errors->first('description') ? "is-invalid" : ""}}" value="{{old('description')}}" required></textarea>
                                <div class="invalid-feedback"> {{$errors->first('description')}}</div>
                            </div>
                            <div class="mb-1">
                                <label for="title" class="font-weight-bold">Weight</label>
                                <input type="text" name="weight" placeholder="100 gr" class="form-control {{$errors->first('weight') ? "is-invalid" : ""}}" value="{{old('weight')}}" required>

                            </div>
                            <div class="mb-1" >
                                <label for="title" class="font-weight-bold">Price</label>
                                <input type="number" name="price" placeholder="10000" class="form-control {{$errors->first('price') ? "is-invalid" : ""}}" value="{{old('price')}}" required>
                                <div class="invalid-feedback"> {{$errors->first('price')}}</div>
                            </div>
                            <div class="mb-1">
                                <label for="slug" class="font-weight-bold">Image 300 x 300 pixel</label>
                                <input type="file" name="image" class="form-control {{$errors->first('image') ? "is-invalid" : ""}}" required>
                                <div class="invalid-feedback"> {{$errors->first('image')}}</div>
                            </div>
                            <div class="mb-3 mt-4">
{{--                                <button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>--}}
                                <button class="btn btn-success" name="save_action" value="PUBLISH">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/produk/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Product')

@section('breadcrumbs', 'Product')

@section('second-breadcrumb')
    <li> Edit Product</li>
@endsection

@section('content')
    <!-- table  -->
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">

                        @if (session('success'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{session('success')}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                        @endif

                        <h3 class="text-center mt-3 mb-5">Edit Product</h3>

                        <div class="row">
                            <div class="col-3 mt-4">
                                <div class="card shadow" >
                                    <img src="{{asset('produk_image/'.$produk->image)}}" class="card-img-top" alt="image">
                                </div>
                            </div>
                            <div class="col-9">
                                <form action="{{route('produk.update', [$produk->id])}}" method="POST" class="d-inline" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <p>Product</p>
                                    <div class="col-12">
                                        <div class="mb-1">
                                            <label for="title" class="font-weight-bold">Category</label>
                                            <select name="kategori" id="kategori" class="form-control {{$errors->first('kategori') ? "is-invalid" : ""}}"  value="{{old('kategori')}}">
                                                <option value="Facial Wash">Facial Wash</option>
                                                <option value="Serum">Serum</option>
                                                <option value="Sunscreen">Sunscreen</option>
                                                <option value="Toner">Toner</option>
                                            </select>
                                            {{--                                <input type="text" name="title" placeholder="Product Category..." class="form-control {{$errors->first('kategori') ? "is-invalid" : ""}}" value="{{old('title')}}" required>--}}
                                            <div class="invalid-feedback"> {{$errors->first('kategori')}}</div>
                                        </div>
                                        <div class="mb-1">
                                            <label for="title" class="font-weight-bold">Name</label>
                                            <input type="text" name="title" class="form-control {{$errors->first('title') ? "is-invalid" : ""}}" value="{{$produk->title}}">
                                            <div class="invalid-feedback"> {{$errors->first('title')}}</div>
                                        </div>
                                        <div class="mb-1">
                                            <label for="title" class="font-weight-bold">Description</label>
                                            <textarea type="text" name="description" class="form-control"> {{$produk->description}} </textarea>
                                            <div class="invalid-feedback"> {{$errors->first('description')}}</div>
                                        </div>
                                        <div class="mb-1">
                                            <label for="title" class="font-weight-bold">Weight</label>
                                            <input type="text" name="weight" placeholder="100 gr" class="form-control" value="{{$produk->weight}}">

                                        </div>
                                        <div class="mb-1" >
                                            <label for="title" class="font-weight-bold">Price</label>
                                            <input type="number" name="price" placeholder="10000" class="form-control" value="{{$produk->price}}" >
                                            <div class="invalid-feedback"> {{$errors->first('price')}}</div>
                                        </div>
                                        <label for="title" class="font-weight-bold">Image</label>
                                        <div class="row">
                                            <div class="d-inline col-6" >
                                                <input type="file" name="image">
                                                <br>
                                                <small class="font-italic text-danger" style="font-size:11px; ">Leave blank if you don't want to change your avatar</small>
                                            </div>
                                            <div class="col-5 d-inline">
                                                <button type="submit" class="btn btn-success top-0"> Update</button>
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    <!-- /table -->
@endsection

@section('script')
@endsection

resources/views/produk/index.blade.php
@extends('layouts.admin')

@section('title', 'Product')

@section('breadcrumbs', 'Overview Product')

@section('css')
    <style>
        .underline:hover{
            text-decoration: underline;
        }
    </style>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    {{-- button create --}}
                    <div class="mb-5 text-right">
                        <a href="{{route('produk.create')}}" class="btn btn-sm btn-success"> <i class="fa fa-plus"></i> Create</a>
                    </div>
                    {{-- alert --}}
                    @if (session('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{session('success')}}.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                    @endif

                    {{-- table --}}
                    <table class="table">
                        <thead class="text-light" style="background-color:#33b751 !important">
                        <tr>
                            {{-- <th width="12px">No</th> --}}
                            <th class="">Kategori</th>
                            <th width="160px">Image</th>
                            <th class="">Name</th>
                            <th class="">Description</th>
                            <th class="">Weight</th>
                            <th class="">Price</th>
                            <th width="150px"></th>
                            <th width="88px">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($produk as $index => $produk)

                            <tr>
                                {{-- <td>{{$index+1}}</td> --}}
                                <td>
                                    <a style="color:#00838f;" class="underline" target="_blank">
                                        <span class="d-block">{{$produk->kategori}}</span>
                                    </a>
                                </td>
                                <td align="left">
                                    @if($produk->image)
                                        <img src="{{asset('produk_image/'.$produk->image)}}" alt="" width="80px">
                                    @endif
                                </td>
                                <td>
                                    <a style="color:#00838f;" class="underline" target="_blank">
                                        <span class="d-block">{{$produk->title}}</span>
                                    </a>
                                </td>
                                <td>
                                    <a  style="color:#00838f;" class="underline" target="_blank">
                                        <span class="d-block">{{$produk->description}}</span>
                                    </a>
                                </td>
                                <td>
                                    <a style="color:#00838f;" class="underline" target="_blank">
                                        <span class="d-block">{{$produk->weight}}</span>
                                    </a>
                                </td>
                                <td>
                                    <a style="color:#00838f;" class="underline" target="_blank">
                                        <span class="d-block">{{$produk->price}}</span>
                                    </a>
                                </td>
                                <td class="text-right pr-4">
                                    @if ($produk->status=='DRAFT')
                                        <span class="font-italic text-danger">Draft</span>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('produk.edit', [$produk->id])}}" class="bnt btn-sm btn-warning text-light" title="Edit"><i class="fa fa-pencil"></i></a>
                                    <button class="btn btn-sm btn-danger" onclick="deleteConfirm('{{$produk->id}}', '{{$produk->title}}')" data-target="#modalDelete" data-toggle="modal"><i class="fa fa-trash"></i></button>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
{{--                        {{$slides->appends(Request::all())->links()}}--}}
                        </tfoot>
                    </table>
                </div>

            </div>
        </div>
    </div>


    <!-- Modal Delete -->
    <div class="modal fade" id="modalDelete" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title d-inline">Delete Product</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="message">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <form action="" id="url" method="POST" class="d-inline">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal Delete -->


@endsection

@section('script')
    <script>
        function deleteConfirm(id, name){
            var url = '{{ route("produk.destroy", ":id") }}';
            url = url.replace(':id', id);
            document.getElementById("url").setAttribute("action", url);
            document.getElementById('message').innerHTML ="Are you sure want to delete Product<b>"+name+"</b> ?"
            $('#modalDelete').modal();
        }

    </script>
@endsection