routes/web.php
<?php

Route::get('/', function(){return redirect('/home');});
Route::get('/home', 'UserController@home')->name('home');
Route::get('/blog', 'UserController@blog')->name('blog');
Route::get('/blog/{slug}', 'UserController@show_article')->name('blog.show');
Route::get('/destination', 'UserController@destination')->name('destination');
Route::get('/destination/{slug}', 'UserController@show_destination')->name('destination.show');
Route::get('/produk/{slug}', 'UserController@show_produk')->name('user.show_produk');
Route::get('/artikel/{slug}', 'UserController@show_artikel')->name('user.show_artikel');
Route::get('/contact', 'UserController@contact')->name('contact');
Route::get('/slide', 'UserController@slide')->name('slide');

Route::prefix('admin')->group(function(){

  Route::get('/', function(){
    return view('auth/login');
  });

  // handle route register
  Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
  })->name("register");

  Auth::routes();

  // Route Dashboard
  Route::get('/dashboard', 'DashboardController@index')->middleware('auth');

  // route categories
  Route::get('/categories/{category}/restore', 'CategoryController@restore')->name('categories.restore');
  Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');
  Route::get('/ajax/categories/search', 'CategoryController@ajaxSearch');
  Route::resource('categories', 'CategoryController')->middleware('auth');

  // route article
  Route::post('/articles/upload', 'ArticleController@upload')->name('articles.upload')->middleware('auth');
  Route::resource('/articles', 'ArticleController')->middleware('auth');

  // route destination
  Route::resource('/destinations', 'DestinationController')->middleware('auth');

  // Route about
  Route::get('/abouts', 'AboutController@index')->name('abouts.index')->middleware('auth');
  Route::get('/abouts/{about}/edit', 'AboutController@edit')->name('abouts.edit')->middleware('auth');
  Route::put('/abouts/{about}', 'AboutController@update')->name('abouts.update')->middleware('auth');
  // Route::resource('abouts', 'AboutController')->middleware('auth');

    // Route slide
    Route::resource('/slide', 'SlideController')->middleware('auth');
    Route::get('/slide', 'SlideController@index')->name('slide.index')->middleware('auth');
    Route::get('/slide/{slide}/edit', 'SlideController@edit')->name('slide.edit')->middleware('auth');
    Route::put('/slide/{slide}', 'SlideController@update')->name('slide.update')->middleware('auth');

    // Route online
    Route::resource('/online', 'OnlineController')->middleware('auth');
    Route::get('/online', 'OnlineController@index')->name('online.index')->middleware('auth');
    Route::get('/online/{online}/edit', 'OnlineController@edit')->name('online.edit')->middleware('auth');
    Route::put('/online/{online}', 'OnlineController@update')->name('online.update')->middleware('auth');

    // Route sosmed
    Route::resource('/sosmed', 'SosmedController')->middleware('auth');
    Route::get('/sosmed', 'SosmedController@index')->name('sosmed.index')->middleware('auth');
    Route::get('/sosmed/{sosmed}/edit', 'SosmedController@edit')->name('sosmed.edit')->middleware('auth');
    Route::put('/sosmed/{sosmed}', 'SosmedController@update')->name('sosmed.update')->middleware('auth');

    // Route layout
    Route::resource('/layout', 'LayoutController')->middleware('auth');
    Route::get('/layout', 'LayoutController@index')->name('layout.index')->middleware('auth');
    Route::get('/layout/{layout}/edit', 'LayoutController@edit')->name('layout.edit')->middleware('auth');
    Route::put('/layout/{layout}', 'LayoutController@update')->name('layout.update')->middleware('auth');

    // Route layout
    Route::resource('/produk', 'ProdukController')->middleware('auth');
    Route::get('/produk', 'ProdukController@index')->name('produk.index')->middleware('auth');
    Route::get('/produk/{produk}/edit', 'ProdukController@edit')->name('produk.edit')->middleware('auth');
    Route::put('/produk/{produk}', 'ProdukController@update')->name('produk.update')->middleware('auth');

    // Route artikel
    Route::resource('/artikel', 'ArtikelController')->middleware('auth');
    Route::get('/artikel', 'ArtikelController@index')->name('artikel.index')->middleware('auth');
    Route::get('/artikel/{artikel}/edit', 'ArtikelController@edit')->name('artikel.edit')->middleware('auth');
    Route::put('/artikel/{artikel}', 'ArtikelController@update')->name('artikel.update')->middleware('auth');
});

app/Destination.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Destination extends Model
{
    //
}

app/Http/Controllers/DestinationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Destination;
use File;

class DestinationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status     = $request->get('status');
        $keyword    = $request->get('keyword') ? $request->get('keyword') : '';
        $category   = $request->get('c') ? $request->get('c') : '';

        if($status){
            $destinations = Destination::where('status', strtoupper($status))
                                        ->where('title', 'LIKE', "%$keyword%")
                                        ->orderBy('created_at', 'desc')
                                        ->paginate(10);

        }else{
            $destinations = Destination::where('title', 'LIKE', "%$keyword%")
                                    ->orderBy('created_at', 'desc')
                                    ->paginate(10);
        }

        return view('Destinations.index', compact('destinations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('destinations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Validator::make($request->all(),[
            'title'      => 'required|min:2|max:200',
            'image'      => 'required',
        ])->validate();

        $new_Destination               = new \App\Destination;
        $new_Destination->title        = $request->get('title');
        $new_Destination->slug         = \Str::slug($request->get('title'), '-');
        $new_Destination->content      = $request->get('content');
        $new_Destination->create_by    = \Auth::user()->id;
        $new_Destination->status       = $request->get('save_action');

        if($request->file('image')){
            $nama_file = time()."_".$request->file('image')->getClientOriginalName();
            $image_path = $request->file('image')->move('destinations_image', $nama_file);
            $new_Destination->image = $nama_file;
        }


        $new_Destination->save();

        return redirect()->route('destinations.index')->with('success', 'Destination successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $destination = Destination::findOrFail($id);
        return view('destinations.edit', compact('destination'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $destination = Destination::findOrFail($id);

        $destination->title        = $request->get('title');
        $destination->slug         = \Str::slug($request->get('title'), '-');
        $destination->content      = $request->get('content');
        $destination->status       = $request->get('save_action');
        $destination->update_by    = \Auth::user()->id;

        if($request->file('image')){
            if($destination->image){
                File::delete('destinations_image/'.$destination->image);
            }
            $nama_file = time()."_".$request->file('image')->getClientOriginalName();
            $new_image = $request->file('image')->move('destinations_image', $nama_file);
            $destination->image = $nama_file;
        }

        $destination->save();
        return redirect()->route('destinations.index')->with('success', 'Destination successfully update.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $destination = Destination::findOrFail($id);
        if($destination->image){
            File::delete('destinations_image/'.$destination->image);
        }
        $destination->forceDelete();

        return redirect()->route('destinations.index')->with('success', 'Destination successfully deleted.');
    }
}

resources/views/destinations/create.blade.php
@extends('layouts.admin')

@section('title', 'Create Destination')

@section('breadcrumbs', 'Destinations' )

@section('second-breadcrumb')
    <li>Create</li>
@endsection

@section('css')
    <script src="/templateEditor/ckeditor/ckeditor.js"></script> 
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-12 mb-3">
                        <h3 align="center"></h3>
                    </div>
                    <form action="{{route('destinations.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="col-10">
                            <div class="mb-4">
                                <label for="title" class="font-weight-bold">Title</label>
                                <input type="text" name="title" placeholder="Destination Title..." class="form-control {{$errors->first('title') ? "is-invalid" : ""}}" value="{{old('title')}}" required>
                                <div class="invalid-feedback"> {{$errors->first('title')}}</div>
                            </div>
                            <div class="mb-3">
                                <label for="slug" class="font-weight-bold">Image</label>
                                <input type="file" name="image" class="form-control {{$errors->first('image') ? "is-invalid" : ""}}" required>
                                <div class="invalid-feedback"> {{$errors->first('image')}}</div>
                            </div>
                            <div class="mb-3">
                                <label for="content" class="font-weight-bold">Content</label>
                                <textarea id="content" class="form-control ckeditor" name="content" rows="10" cols="50"></textarea>
                            </div>
                            
                            <div class="mb-3 mt-4">
                                <button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>
                                <button class="btn btn-success" name="save_action" value="PUBLISH">Publish</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('script')
    {{-- ckeditor --}}
    <script>
        CKEDITOR.replace( 'content', {
            filebrowserUploadUrl    : "{{route('articles.upload', ['_token' => csrf_token()])}}",
            filebrowserUploadMethod : 'form'
        });
    </script>
@endsection

resources/views/destinations/edit.blade.php
@extends('layouts.admin')

@section('title', 'Destination')

@section('breadcrumbs', 'Edit Destination')

@section('second-breadcrumb')
    <li>Edit</li>
@endsection

@section('css')
    <script src="/templateEditor/ckeditor/ckeditor.js"></script> 
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-12 mb-3">
                        <h3 align="center"></h3>
                    </div>
                    <form action="{{route('destinations.update', [$destination->id])}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="col-10">
                            <div class="mb-4">
                                <label for="title" class="font-weight-bold">Title</label>
                                <input type="text" name="title" placeholder="Destination Title..." class="form-control {{$errors->first('title') ? "is-invalid" : ""}}" value="{{$destination->title}}" required>
                                <div class="invalid-feedback"> {{$errors->first('title')}}</div>
                            </div>
                            <div class="mb-3">
                                <label for="image" class="font-weight-bold d-flex">Image</label>
                                @if($destination->image)
                                    <img src="{{asset('destinations_image/'.$destination->image)}}" alt="" width="120px">
                                @else   
                                    No Image
                                @endif
                                <input type="file" name="image" class="form-control mt-2" >
                                <small class="text-muted">Kosongkan jika tidak ingin mengubah gambar.</small>
                            </div>
                            
                            <div class="mb-3">
                                <label for="content" class="font-weight-bold">Content</label>
                                <textarea id="content" class="form-control ckeditor" name="content" rows="10" cols="50">{{$destination->content}}</textarea>
                            </div>
                            <div class="mb-3 mt-4">
                                <button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>
                                <button class="btn btn-success" name="save_action" value="PUBLISH">Publish</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    {{-- ckeditor --}}
    <script>
        CKEDITOR.replace( 'content', {
            filebrowserUploadUrl    : "{{route('articles.upload', ['_token' => csrf_token()])}}",
            filebrowserUploadMethod : 'form'
        });
    </script>
@endsection

resources/views/destinations/index.blade.php
@extends('layouts.admin')

@section('title', 'Destinations')

@section('breadcrumbs', 'Overview Destinations')

@section('css')
    <style>
        .underline:hover{
            text-decoration: underline;
        }
    </style>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    
                    {{-- button create --}}
                    <div class="mb-5 text-right">
                        <a href="{{route('destinations.create')}}" class="btn btn-sm btn-success"> <i class="fa fa-plus"></i> Create</a>
                    </div>

                    {{-- display filter --}}
                    <div class="row mb-3">
                        <div class="col-sm-7">
                            <ul class="nav nav-tabs ">
                                <li class="nav-item">
                                    <a class="nav-link p-2 px-3 {{Request::get('status') == NULL ? 'active' : ''}}" href="{{route('destinations.index')}}">All</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link p-2 px-3 {{Request::get('status') == 'publish' ?'active' : '' }}" href="{{route('destinations.index', ['status' =>'publish'])}}">Publish</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link p-2 px-3 {{Request::get('status') == 'draft' ?'active' : '' }}" href="{{route('destinations.index', ['status' =>'draft'])}}">Draft</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-5">
                            <form action="{{route('destinations.index')}}">
                                <div class="input-group">
                                    <input name="keyword" type="text" value="{{Request::get('keyword')}}" class="form-control" placeholder="Filter by title">
                                    <div class="input-group-append">
                                        <input type="submit" value="Filter" class="btn btn-info">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    {{-- alert --}}
                    @if (session('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{session('success')}}.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                    @endif
                    
                    {{-- table --}}
                    <table class="table">
                        <thead class="text-light" style="background-color:#33b751 !important">
                            <tr>
                                {{-- <th width="12px">No</th> --}}
                                <th width="160px">Image</th>
                                <th class="">Destination Title</th>
                                <th width="150px"></th>
                                <th width="88px">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($destinations as $index => $destination)                            
                                
                                <tr>
                                    {{-- <td>{{$index+1}}</td> --}}
                                    <td align="left">
                                        @if($destination->image)
                                            <img src="{{asset('destinations_image/'.$destination->image)}}" alt="" width="120px">
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{route('destinations.edit', [$destination->id])}}" style="color:#00838f;" class="underline">
                                            <span class="d-block">{{$destination->title}}</span>
                                        </a>
                                    </td>
                                    <td class="text-right pr-4">
                                        @if ($destination->status=='DRAFT')
                                            <span class="font-italic text-danger">Draft</span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{route('destinations.edit', [$destination->id])}}" class="bnt btn-sm btn-warning text-light" title="Edit"><i class="fa fa-pencil"></i></a>
                                        <button class="btn btn-sm btn-danger" onclick="deleteConfirm('{{$destination->id}}', '{{$destination->title}}')" data-target="#modalDelete" data-toggle="modal"><i class="fa fa-trash"></i></button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            {{$destinations->appends(Request::all())->links()}}
                        </tfoot>
                    </table>
                </div>

            </div>
        </div>
    </div>


    <!-- Modal Delete -->
        <div class="modal fade" id="modalDelete" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title d-inline">Delete Destination</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="message">

                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form action="" id="url" method="POST" class="d-inline">
                    @csrf 
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                </div>
            </div>
            </div>
        </div>
    <!-- End Modal Delete -->


@endsection

@section('script')
    <script>
        function deleteConfirm(id, name){ 
            var url = '{{ route("destinations.destroy", ":id") }}';    
                url = url.replace(':id', id);
            document.getElementById("url").setAttribute("action", url);
            document.getElementById('message').innerHTML ="Are you sure want to delete destination <b>"+name+"</b> ?"
            $('#modalDelete').modal();
        }

    </script>
@endsection