routes/web.php
<?php

Route::get('/', function(){return redirect('/home');});
Route::get('/home', 'UserController@home')->name('home');
Route::get('/blog', 'UserController@blog')->name('blog');
Route::get('/blog/{slug}', 'UserController@show_article')->name('blog.show');
Route::get('/destination', 'UserController@destination')->name('destination');
Route::get('/destination/{slug}', 'UserController@show_destination')->name('destination.show');
Route::get('/produk/{slug}', 'UserController@show_produk')->name('user.show_produk');
Route::get('/artikel/{slug}', 'UserController@show_artikel')->name('user.show_artikel');
Route::get('/contact', 'UserController@contact')->name('contact');
Route::get('/slide', 'UserController@slide')->name('slide');

Route::prefix('admin')->group(function(){

  Route::get('/', function(){
    return view('auth/login');
  });

  // handle route register
  Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
  })->name("register");

  Auth::routes();

  // Route Dashboard
  Route::get('/dashboard', 'DashboardController@index')->middleware('auth');

  // route categories
  Route::get('/categories/{category}/restore', 'CategoryController@restore')->name('categories.restore');
  Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');
  Route::get('/ajax/categories/search', 'CategoryController@ajaxSearch');
  Route::resource('categories', 'CategoryController')->middleware('auth');

  // route article
  Route::post('/articles/upload', 'ArticleController@upload')->name('articles.upload')->middleware('auth');
  Route::resource('/articles', 'ArticleController')->middleware('auth');

  // route destination
  Route::resource('/destinations', 'DestinationController')->middleware('auth');

  // Route about
  Route::get('/abouts', 'AboutController@index')->name('abouts.index')->middleware('auth');
  Route::get('/abouts/{about}/edit', 'AboutController@edit')->name('abouts.edit')->middleware('auth');
  Route::put('/abouts/{about}', 'AboutController@update')->name('abouts.update')->middleware('auth');
  // Route::resource('abouts', 'AboutController')->middleware('auth');

    // Route slide
    Route::resource('/slide', 'SlideController')->middleware('auth');
    Route::get('/slide', 'SlideController@index')->name('slide.index')->middleware('auth');
    Route::get('/slide/{slide}/edit', 'SlideController@edit')->name('slide.edit')->middleware('auth');
    Route::put('/slide/{slide}', 'SlideController@update')->name('slide.update')->middleware('auth');

    // Route online
    Route::resource('/online', 'OnlineController')->middleware('auth');
    Route::get('/online', 'OnlineController@index')->name('online.index')->middleware('auth');
    Route::get('/online/{online}/edit', 'OnlineController@edit')->name('online.edit')->middleware('auth');
    Route::put('/online/{online}', 'OnlineController@update')->name('online.update')->middleware('auth');

    // Route sosmed
    Route::resource('/sosmed', 'SosmedController')->middleware('auth');
    Route::get('/sosmed', 'SosmedController@index')->name('sosmed.index')->middleware('auth');
    Route::get('/sosmed/{sosmed}/edit', 'SosmedController@edit')->name('sosmed.edit')->middleware('auth');
    Route::put('/sosmed/{sosmed}', 'SosmedController@update')->name('sosmed.update')->middleware('auth');

    // Route layout
    Route::resource('/layout', 'LayoutController')->middleware('auth');
    Route::get('/layout', 'LayoutController@index')->name('layout.index')->middleware('auth');
    Route::get('/layout/{layout}/edit', 'LayoutController@edit')->name('layout.edit')->middleware('auth');
    Route::put('/layout/{layout}', 'LayoutController@update')->name('layout.update')->middleware('auth');

    // Route layout
    Route::resource('/produk', 'ProdukController')->middleware('auth');
    Route::get('/produk', 'ProdukController@index')->name('produk.index')->middleware('auth');
    Route::get('/produk/{produk}/edit', 'ProdukController@edit')->name('produk.edit')->middleware('auth');
    Route::put('/produk/{produk}', 'ProdukController@update')->name('produk.update')->middleware('auth');

    // Route artikel
    Route::resource('/artikel', 'ArtikelController')->middleware('auth');
    Route::get('/artikel', 'ArtikelController@index')->name('artikel.index')->middleware('auth');
    Route::get('/artikel/{artikel}/edit', 'ArtikelController@edit')->name('artikel.edit')->middleware('auth');
    Route::put('/artikel/{artikel}', 'ArtikelController@update')->name('artikel.update')->middleware('auth');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    public function categories(){
        // return $this->belongsToMany(Category::class)->withPivot('category_id');
        return $this->belongsToMany('App\Category')->withPivot('category_id');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Category;

use App\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status     = $request->get('status');
        $keyword    = $request->get('keyword') ? $request->get('keyword') : '';
        $category   = $request->get('c') ? $request->get('c') : '';

        if($status){
            // $articles = \App\Article::where('status', strtoupper($status))->where('title', 'LIKE', "%$keyword%")->paginate(10);
            $articles = Article::with('categories')
                                    ->whereHas('categories', function($q) use($category){
                                        $q->where('name', 'LIKE', "%$category%");
                                    })
                                    ->where('status', strtoupper($status))
                                    ->where('title', 'LIKE', "%$keyword%")
                                    ->orderBy('created_at', 'desc')
                                    ->paginate(10);

        }else{
            // $articles = \App\Article::with('categories')->where('title', 'LIKE', "%$keyword%")->paginate(10);
            $articles = Article::with('categories')
                                    ->whereHas('categories', function($q) use($category) {
                                        $q->where('name', 'LIKE', "%$category%"); 
                                    })
                                    ->where('title', 'LIKE', "%$keyword%")
                                    ->orderBy('created_at', 'desc')
                                    ->paginate(10);
        }

        return view('articles.index', ['articles'=>$articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Validator::make($request->all(),[
            'title'      => 'required|min:2|max:200'
        ])->validate();

        $new_articles               = new \App\Article;
        $new_articles->title        = $request->get('title');
        $new_articles->slug         = \Str::slug($request->get('title'), '-');
        $new_articles->content      = $request->get('content');
        $new_articles->create_by    = \Auth::user()->id;
        $new_articles->status       = $request->get('save_action');
        $new_articles->save();
        
        // save in table article category
        $new_articles->categories()->attach($request->get('categories'));

        return redirect()->route('articles.index')->with('success', 'Article successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = \App\Article::findOrFail($id);
        return view('articles.edit', ['article'=>$article]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $article = \App\Article::findOrFail($id);

        $article->title        = $request->get('title');
        $article->slug         = \Str::slug($request->get('title'), '-');
        $article->content      = $request->get('content');
        $article->status       = $request->get('save_action');
        $article->update_by    = \Auth::user()->id;

        $article->categories()->sync($request->get('categories'));

        $article->save();
        return redirect()->route('articles.index')->with('success', 'Category successfully update.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = \App\Article::findOrFail($id);
        $article->forceDelete();

        return redirect()->route('articles.index')->with('success', 'Article permanenly delete');
    }

    public function upload(Reques $request){
        if($request->hasFile('upload')) {
            // $originName = $request->file('upload')->getClientOriginalName();
            // $fileName   = pathinfo($originName, PATHINFO_FILENAME);
            // $extension  = $request->file('upload')->getClientOriginalExtension();
            // $fileName   = $fileName.'_'.time().'.'.$extension;

            // $request->file('upload')->move(public_path('images'), $fileName);

            // $CKEditorFuncNum = $request->input('CKEditorFuncNum');
            
            // $url = asset('images/'.$fileName); 
            // $msg = 'Image uploaded successfully'; 

            // $response = "<script>window.parent.CKEDITOR.tools.callFunction($CKEditorFuncNum, '$url', '$msg')</script>";
            // @header('Content-type: text/html; charset=utf-8'); 

            // echo $response;

        }
    }


}

resources/views/articles/create.blade.php
@extends('layouts.admin')

@section('title', 'Create Article')

@section('breadcrumbs', 'Articles' )

@section('second-breadcrumb')
    <li>Create</li>
@endsection

@section('css')
    <script src="/templateEditor/ckeditor/ckeditor.js"></script> 
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-12 mb-3">
                        <h3 align="center"></h3>
                    </div>
                    <form action="{{route('articles.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="col-10">
                            <div class="mb-4">
                                <label for="title" class="font-weight-bold">Title</label>
                                <input type="text" name="title" placeholder="Article Title" class="form-control {{$errors->first('title') ? "is-invalid" : ""}}" value="{{old('title')}}" required>
                                <div class="invalid-feedback"> {{$errors->first('title')}}</div>
                            </div>
                            <div class="mb-3">
                                <label for="category" class="font-weight-bold">Category</label>
                                <select class="form-control" name="categories[]" id="categories" multiple></select>
                            </div>
                            <div class="mb-3">
                                <label for="content" class="font-weight-bold">Content</label>
                                <textarea id="content" class="form-control ckeditor" name="content" rows="10" cols="50"></textarea>
                            </div>
                            
                            <div class="mb-3 mt-4">
                                <button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>
                                <button class="btn btn-success" name="save_action" value="PUBLISH">Publish</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('script')
    {{-- ckeditor --}}
    <script>
        CKEDITOR.replace( 'content', {
            filebrowserUploadUrl    : "{{route('articles.upload', ['_token' => csrf_token()])}}",
            filebrowserUploadMethod : 'form'
        });
    </script>

    {{-- select --}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        $('#categories').select2({
            ajax    : {
                url             : '{{url("/admin/ajax/categories/search")}}',
                processResults  : function(data){
                    return {
                        results : data.map(function(item){
                            return {id:item.id, text:item.name}
                        })
                    }
                }
            }
        });
    </script>

@endsection

resources/views/articles/edit.blade.php
@extends('layouts.admin')

@section('title', 'Article')

@section('breadcrumbs', 'Edit Article')

@section('second-breadcrumb')
    <li>Edit</li>
@endsection

@section('css')
    <script src="/templateEditor/ckeditor/ckeditor.js"></script> 
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-12 mb-3">
                        <h3 align="center"></h3>
                    </div>
                    <form action="{{route('articles.update', [$article->id])}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="_method" value="PUT">
                        <div class="col-10">
                            <div class="mb-4">
                                <label for="title" class="font-weight-bold">Title</label>
                                <input type="text" name="title" placeholder="Article Title" class="form-control {{$errors->first('title') ? "is-invalid" : ""}}" value="{{$article->title}}" required>
                                <div class="invalid-feedback"> {{$errors->first('title')}}</div>
                            </div>
                            <div class="mb-3">
                                <label for="category" class="d-block font-weight-bold">Category</label>
                                <select name="categories[]" id="categories" multiple class="col-12"></select>
                            </div>
                            <div class="mb-3">
                                <label for="content" class="font-weight-bold">Content</label>
                                <textarea id="content" class="form-control ckeditor" name="content" rows="10" cols="50">{{$article->content}}</textarea>
                            </div>
                            <div class="mb-3 mt-4">
                                <button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>
                                <button class="btn btn-success" name="save_action" value="PUBLISH">Publish</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    {{-- ckeditor --}}
    <script>
        CKEDITOR.replace( 'content', {
            filebrowserUploadUrl    : "{{route('articles.upload', ['_token' => csrf_token()])}}",
            filebrowserUploadMethod : 'form'
        });
    </script>

    {{-- category select2 --}}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <script>
        $('#categories').select2({
            ajax: {
                url             : '{{url("/admin/ajax/categories/search")}}',
                processResults  : function(data){
                    return {
                        results: data.map(function(item){return {id: item.id, text: item.name} })
                    }
                }
            }
        });

        var categories = {!! $article->categories !!}

            categories.forEach(function(category){
                var option = new Option(category.name, category.id, true, true);
                $('#categories').append(option).trigger('change');
            });
    </script>


@endsection

resources/views/articles/index.blade.php
@extends('layouts.admin')

@section('title', 'Articles')

@section('breadcrumbs', 'Overview Articles')

@section('css')
    <style>
        .underline:hover{
            text-decoration: underline;
        }
    </style>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    
                    {{-- button create --}}
                    <div class="mb-5 text-right">
                        <a href="{{route('articles.create')}}" class="btn btn-sm btn-success"> <i class="fa fa-plus"></i> Create</a>
                    </div>

                    {{-- display filter --}}
                    <div class="row mb-3">
                        <div class="col-sm-7">
                            <ul class="nav nav-tabs ">
                                <li class="nav-item">
                                    <a class="nav-link p-2 px-3 {{Request::get('status') == NULL ? 'active' : ''}}" href="{{route('articles.index')}}">All</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link p-2 px-3 {{Request::get('status') == 'publish' ?'active' : '' }}" href="{{route('articles.index', ['status' =>'publish'])}}">Publish</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link p-2 px-3 {{Request::get('status') == 'draft' ?'active' : '' }}" href="{{route('articles.index', ['status' =>'draft'])}}">Draft</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-5">
                            <form action="{{route('articles.index')}}">
                                <div class="input-group">
                                    <input name="keyword" type="text" value="{{Request::get('keyword')}}" class="form-control" placeholder="Filter by title">
                                    <div class="input-group-append">
                                        <input type="submit" value="Filter" class="btn btn-info">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    {{-- alert --}}
                    @if (session('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{session('success')}}.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                    @endif
                    
                    {{-- table --}}
                    <table class="table">
                        <thead class="text-light" style="background-color:#33b751 !important">
                            <tr>
                                <th width="12px">No</th>
                                <th class="text-center">Article Title</th>
                                <th width="150px"></th>
                                <th width="88px">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($articles as $index => $article)                            
                                
                                <tr>
                                    <td>{{$index+1}}</td>
                                    <td>
                                        <a href="{{route('articles.edit', [$article->id])}}" style="color:#00838f;" class="underline">
                                            <span class="d-block">{{$article->title}}</span>
                                        </a>


                                        @foreach($article->categories as $value)
                                            <a class="d-inline underline" href="{{route('articles.index', ['c' =>$value->name])}}">
                                                <span class="text-muted font-italic" style="font-size:10px; margin-top:10px ;line-height: 60%">{{$value->name}},</span>
                                            </a>
                                        @endforeach
                                    </td>
                                    <td class="text-right pr-4">
                                        @if ($article->status=='DRAFT')
                                            <span class="font-italic text-danger">Draft</span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{route('articles.edit', [$article->id])}}" class="bnt btn-sm btn-warning text-light" title="Edit"><i class="fa fa-pencil"></i></a>
                                        <form class="d-inline" method="POST" action="{{route('articles.destroy', [$article->id])}}" >
                                            @method('delete')
                                            @csrf   
                                            <button type="submit" class="btn btn-sm btn-danger " title="Delete"><i class="fa fa-trash"></i></button>

                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            {{$articles->appends(Request::all())->links()}}
                        </tfoot>
                    </table>
                </div>

            </div>
        </div>
    </div>
@endsection

@section('script')
    
@endsection